
package com.genesyslab.gskm.services;

import org.datacontract.schemas._2004._07.gskm_services_datatransfer.CreateUsersRequest;
import org.datacontract.schemas._2004._07.gskm_services_datatransfer.DeleteUsersRequest;
import org.datacontract.schemas._2004._07.gskm_services_datatransfer.GetRolesRequest;
import org.datacontract.schemas._2004._07.gskm_services_datatransfer.GetUsersRequest;
import org.datacontract.schemas._2004._07.gskm_services_datatransfer.UpdateUsersRequest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPermissionManagement", targetNamespace = "http://genesyslab.com/GSKM/services/")
@XmlSeeAlso({
    ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    org.datacontract.schemas._2004._07.gskm_services.ObjectFactory.class,
    org.datacontract.schemas._2004._07.gskm_services_datatransfer.ObjectFactory.class
})
public interface IPermissionManagement {


    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.gskm_services_datatransfer.GetTenantsResponse
     */
    @WebMethod(operationName = "GetTenants", action = "http://genesyslab.com/GSKM/services/IPermissionManagement/GetTenants")
    @WebResult(name = "GetTenantsResult", targetNamespace = "http://genesyslab.com/GSKM/services/")
    @RequestWrapper(localName = "GetTenants", targetNamespace = "http://genesyslab.com/GSKM/services/", className = "com.genesyslab.gskm.services.GetTenants")
    @ResponseWrapper(localName = "GetTenantsResponse", targetNamespace = "http://genesyslab.com/GSKM/services/", className = "com.genesyslab.gskm.services.GetTenantsResponse")
    public GetTenantsResponse getTenants();

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.gskm_services_datatransfer.GetRolesResponse
     */
    @WebMethod(operationName = "GetRoles", action = "http://genesyslab.com/GSKM/services/IPermissionManagement/GetRoles")
    @WebResult(name = "GetRolesResult", targetNamespace = "http://genesyslab.com/GSKM/services/")
    @RequestWrapper(localName = "GetRoles", targetNamespace = "http://genesyslab.com/GSKM/services/", className = "com.genesyslab.gskm.services.GetRoles")
    @ResponseWrapper(localName = "GetRolesResponse", targetNamespace = "http://genesyslab.com/GSKM/services/", className = "com.genesyslab.gskm.services.GetRolesResponse")
    public GetRolesResponse getRoles(
            @WebParam(name = "request", targetNamespace = "http://genesyslab.com/GSKM/services/")
                    GetRolesRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.gskm_services_datatransfer.GetUsersResponse
     */
    @WebMethod(operationName = "GetUsers", action = "http://genesyslab.com/GSKM/services/IPermissionManagement/GetUsers")
    @WebResult(name = "GetUsersResult", targetNamespace = "http://genesyslab.com/GSKM/services/")
    @RequestWrapper(localName = "GetUsers", targetNamespace = "http://genesyslab.com/GSKM/services/", className = "com.genesyslab.gskm.services.GetUsers")
    @ResponseWrapper(localName = "GetUsersResponse", targetNamespace = "http://genesyslab.com/GSKM/services/", className = "com.genesyslab.gskm.services.GetUsersResponse")
    public GetUsersResponse getUsers(
            @WebParam(name = "request", targetNamespace = "http://genesyslab.com/GSKM/services/")
                    GetUsersRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.gskm_services_datatransfer.CreateUsersResponse
     */
    @WebMethod(operationName = "CreateUsers", action = "http://genesyslab.com/GSKM/services/IPermissionManagement/CreateUsers")
    @WebResult(name = "CreateUsersResult", targetNamespace = "http://genesyslab.com/GSKM/services/")
    @RequestWrapper(localName = "CreateUsers", targetNamespace = "http://genesyslab.com/GSKM/services/", className = "com.genesyslab.gskm.services.CreateUsers")
    @ResponseWrapper(localName = "CreateUsersResponse", targetNamespace = "http://genesyslab.com/GSKM/services/", className = "com.genesyslab.gskm.services.CreateUsersResponse")
    public CreateUsersResponse createUsers(
            @WebParam(name = "request", targetNamespace = "http://genesyslab.com/GSKM/services/")
                    CreateUsersRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.gskm_services_datatransfer.DeleteUsersResponse
     */
    @WebMethod(operationName = "DeleteUsers", action = "http://genesyslab.com/GSKM/services/IPermissionManagement/DeleteUsers")
    @WebResult(name = "DeleteUsersResult", targetNamespace = "http://genesyslab.com/GSKM/services/")
    @RequestWrapper(localName = "DeleteUsers", targetNamespace = "http://genesyslab.com/GSKM/services/", className = "com.genesyslab.gskm.services.DeleteUsers")
    @ResponseWrapper(localName = "DeleteUsersResponse", targetNamespace = "http://genesyslab.com/GSKM/services/", className = "com.genesyslab.gskm.services.DeleteUsersResponse")
    public DeleteUsersResponse deleteUsers(
            @WebParam(name = "request", targetNamespace = "http://genesyslab.com/GSKM/services/")
                    DeleteUsersRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.gskm_services_datatransfer.UpdateUsersResponse
     */
    @WebMethod(operationName = "UpdateUsers", action = "http://genesyslab.com/GSKM/services/IPermissionManagement/UpdateUsers")
    @WebResult(name = "UpdateUsersResult", targetNamespace = "http://genesyslab.com/GSKM/services/")
    @RequestWrapper(localName = "UpdateUsers", targetNamespace = "http://genesyslab.com/GSKM/services/", className = "com.genesyslab.gskm.services.UpdateUsers")
    @ResponseWrapper(localName = "UpdateUsersResponse", targetNamespace = "http://genesyslab.com/GSKM/services/", className = "com.genesyslab.gskm.services.UpdateUsersResponse")
    public UpdateUsersResponse updateUsers(
            @WebParam(name = "request", targetNamespace = "http://genesyslab.com/GSKM/services/")
                    UpdateUsersRequest request);

}
