
package com.genesyslab.gskm.services;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PermissionManagement", targetNamespace = "http://genesyslab.com/GSKM/services/", wsdlLocation = "http://hffgpdna:21001/services/Services.PermissionManagement/PermissionManagement.svc?wsdl")
public class PermissionManagement
    extends Service
{

    private final static URL PERMISSIONMANAGEMENT_WSDL_LOCATION;
    private final static WebServiceException PERMISSIONMANAGEMENT_EXCEPTION;
    private final static QName PERMISSIONMANAGEMENT_QNAME = new QName("http://genesyslab.com/GSKM/services/", "PermissionManagement");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://hffgpdna:21001/services/Services.PermissionManagement/PermissionManagement.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERMISSIONMANAGEMENT_WSDL_LOCATION = url;
        PERMISSIONMANAGEMENT_EXCEPTION = e;
    }

    public PermissionManagement() {
        super(__getWsdlLocation(), PERMISSIONMANAGEMENT_QNAME);
    }

    public PermissionManagement(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERMISSIONMANAGEMENT_QNAME, features);
    }

    public PermissionManagement(URL wsdlLocation) {
        super(wsdlLocation, PERMISSIONMANAGEMENT_QNAME);
    }

    public PermissionManagement(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERMISSIONMANAGEMENT_QNAME, features);
    }

    public PermissionManagement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PermissionManagement(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPermissionManagement
     */
    @WebEndpoint(name = "WSHttpBinding_IPermissionManagement")
    public IPermissionManagement getWSHttpBindingIPermissionManagement() {
        return super.getPort(new QName("http://genesyslab.com/GSKM/services/", "WSHttpBinding_IPermissionManagement"), IPermissionManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPermissionManagement
     */
    @WebEndpoint(name = "WSHttpBinding_IPermissionManagement")
    public IPermissionManagement getWSHttpBindingIPermissionManagement(WebServiceFeature... features) {
        return super.getPort(new QName("http://genesyslab.com/GSKM/services/", "WSHttpBinding_IPermissionManagement"), IPermissionManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERMISSIONMANAGEMENT_EXCEPTION!= null) {
            throw PERMISSIONMANAGEMENT_EXCEPTION;
        }
        return PERMISSIONMANAGEMENT_WSDL_LOCATION;
    }

}
